services:
  # Backend API Service
  - type: web
    name: canyon-ai
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_ORIGINS
        value: https://canyon-ai-1.onrender.com,https://canyon-ai.onrender.com

  # Frontend Next.js Service
  - type: web
    name: canyon-ai-1
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://canyon-ai.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://hdcsxkxohgtpitfljqhx.supabase.co 